--- # document start

# Comments in YAML look like this.

# Views
ListCases: &list_cases
  scheme: Waterfall
  children:
    '0000':
      component: ListComponent
      props:
        title: My Lists
      data:
    '0100':
      component: ListComponent
      props:
        title: My Lists
      data:

# Landing
'00': *list_cases
'/': *list_cases
... # document end
