--- # document start

# Comments in YAML look like this.

# Views
ListCases: &list_cases
  scheme: Waterfall
  mode: Generated
  children:
    '0000':
      component: ExampleFunctionComponent
      props:
        title: My cases
      dataSource:
    '0100':
      component: TextField
      props:
        title: My text
      dataSource:
ListBoards: &list_boards
  generator: ListBoards
  scheme: Waterfall
  children:
    '0000':
      component: ListComponent
      props:
        title: My Boards
      dataSource: useSubscriptionBoard

# Landing
'00': *list_boards
'/cases': *list_cases
'/': *list_boards
... # document end
