--- # document start

# Comments in YAML look like this.

# Views
Views:
  ListProjects: &list_projects
    entity: ListProjects
    category: Component
    children:
      '0000':
        component: ExampleFunctionComponent
        props:
          title: My projects
        dataSource:
      '0100':
        component: TextField
        props:
          title: My text
        dataSource:
  ListBoards: &list_boards
    entity: ListBoards
    category: Mgen
    children:
      '0000':
        component: ListComponent
        props:
          title: My Boards
          addNew: true
          boardCard:
            cUrl: /boards/{id}
            cLayout: TitleOnly
        dataSource: Boards.useSubOwnBoard
        actions:
          createBoard: Boards.createBoard
          viewBoard: Boards.viewBoard
      '0100':
        component: ListComponent
        props:
          title: Other Boards
          boardCard:
            cUrl: /boards/{id}
            cLayout: TitleOnly
        dataSource: Boards.useSubOtherBoard
        actions:
          viewBoard: Boards.viewBoard
  ListCases: &list_cases
    entity: ListCases
    category: Mgen
    children:
      '0000':
        component: ListComponent
        props:
          title: List Cases
        dataSource: Cases.useCases
        actions:
          viewBoard: Cases.viewCase

# Landing
Routes:
  '/': *list_boards
  '/cases': *list_projects
  '/boards/:bid': *list_cases
... # document end
