--- # document start

# Comments in YAML look like this.

# Views
Views:
  Dashboard: &dashboard
    entity: Dashboard
    category: Component
  ListSubjects: &list_subjects
    entity: ListSubjects
    category: Mgen
    children:
      '0000':
        component: PageContextComponent
        actions:
          setClipCss: Visit.addSubject
      '0100':
        component: ListComponent
        props:
          add: true
          addAlt: showInline
          addAltData:
          cardData: ListSubjectsCardData
          cardAltAction: drilldownUrl
          cardAltData: /subjects/{id}
          title: Subjects
        dataSource: Visit.useSubscribeSubjects
        theme: App.useSubjectTheme
        actions:
          addSubject: Visit.addSubject
          viewSubject: Visit.viewSubject
  ListBoards: &list_boards
    entity: ListBoards
    category: Mgen
    children:
      '0000':
        component: ListComponent
        props:
          add: true
          addAlt: showInline
          addAltData:
          cardData: TitleOnly
          cardAltAction: drilldownUrl
          cardAltData: /boards/{id}
          title: Subjects
        dataSource: Boards.useSubOwnBoard
        actions:
          createBoard: Boards.createBoard
          viewBoard: Boards.viewBoard
      '0100':
        component: ListComponent
        props:
          add: false
          addAlt: showInline
          addAltData:
          cardData: TitleOnly
          cardAltAction: showPaneData
          cardAltData: /boards/{id}
          title: Other Boards
        dataSource: Boards.useSubOtherBoard
        actions:
          viewBoard: Boards.viewBoard
  ListCases: &list_cases
    entity: ListCases
    category: Mgen
    children:
      '0000':
        component: ListComponent
        props:
          cardData: TitleOnly
          cardAltAction: showPaneData
          title: List Cases
        dataSource: Cases.useCases
        actions:
          viewBoard: Cases.viewCase
  NotFound: &not_found
    entity: NotFound
    category: Component

# Landing
Routes:
  '/boards/:bid': *list_cases
  '/subjects/:sid': *list_cases
  '/subjects': *list_subjects
  '/': *dashboard
  '/notfound': *not_found # if all else fails
... # document end
